// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: wasmmessages.proto

package pluginmanager

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WasmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Optional      map[string]string      `protobuf:"bytes,3,rep,name=optional,proto3" json:"optional,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmRequest) Reset() {
	*x = WasmRequest{}
	mi := &file_wasmmessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmRequest) ProtoMessage() {}

func (x *WasmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wasmmessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmRequest.ProtoReflect.Descriptor instead.
func (*WasmRequest) Descriptor() ([]byte, []int) {
	return file_wasmmessages_proto_rawDescGZIP(), []int{0}
}

func (x *WasmRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WasmRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *WasmRequest) GetOptional() map[string]string {
	if x != nil {
		return x.Optional
	}
	return nil
}

func (x *WasmRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WasmRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WasmRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_wasmmessages_proto protoreflect.FileDescriptor

const file_wasmmessages_proto_rawDesc = "" +
	"\n" +
	"\x12wasmmessages.proto\"\xdf\x02\n" +
	"\vWasmRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12<\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x1c.WasmRequest.ParametersEntryR\n" +
	"parameters\x126\n" +
	"\boptional\x18\x03 \x03(\v2\x1a.WasmRequest.OptionalEntryR\boptional\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rOptionalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\tZ\a./protob\x06proto3"

var (
	file_wasmmessages_proto_rawDescOnce sync.Once
	file_wasmmessages_proto_rawDescData []byte
)

func file_wasmmessages_proto_rawDescGZIP() []byte {
	file_wasmmessages_proto_rawDescOnce.Do(func() {
		file_wasmmessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wasmmessages_proto_rawDesc), len(file_wasmmessages_proto_rawDesc)))
	})
	return file_wasmmessages_proto_rawDescData
}

var file_wasmmessages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wasmmessages_proto_goTypes = []any{
	(*WasmRequest)(nil), // 0: WasmRequest
	nil,                 // 1: WasmRequest.ParametersEntry
	nil,                 // 2: WasmRequest.OptionalEntry
}
var file_wasmmessages_proto_depIdxs = []int32{
	1, // 0: WasmRequest.parameters:type_name -> WasmRequest.ParametersEntry
	2, // 1: WasmRequest.optional:type_name -> WasmRequest.OptionalEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wasmmessages_proto_init() }
func file_wasmmessages_proto_init() {
	if File_wasmmessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wasmmessages_proto_rawDesc), len(file_wasmmessages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wasmmessages_proto_goTypes,
		DependencyIndexes: file_wasmmessages_proto_depIdxs,
		MessageInfos:      file_wasmmessages_proto_msgTypes,
	}.Build()
	File_wasmmessages_proto = out.File
	file_wasmmessages_proto_goTypes = nil
	file_wasmmessages_proto_depIdxs = nil
}
