// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: Envelop.proto

package global

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	OriginPeerId  string                 `protobuf:"bytes,7,opt,name=origin_peer_id,json=originPeerId,proto3" json:"origin_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelop) Reset() {
	*x = Envelop{}
	mi := &file_Envelop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelop) ProtoMessage() {}

func (x *Envelop) ProtoReflect() protoreflect.Message {
	mi := &file_Envelop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelop.ProtoReflect.Descriptor instead.
func (*Envelop) Descriptor() ([]byte, []int) {
	return file_Envelop_proto_rawDescGZIP(), []int{0}
}

func (x *Envelop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelop) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Envelop) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelop) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelop) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Envelop) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Envelop) GetOriginPeerId() string {
	if x != nil {
		return x.OriginPeerId
	}
	return ""
}

var File_Envelop_proto protoreflect.FileDescriptor

const file_Envelop_proto_rawDesc = "" +
	"\n" +
	"\rEnvelop.proto\"\xc6\x01\n" +
	"\aEnvelop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\x12$\n" +
	"\x0eorigin_peer_id\x18\a \x01(\tR\foriginPeerIdB\x10Z\x0e./proto;globalb\x06proto3"

var (
	file_Envelop_proto_rawDescOnce sync.Once
	file_Envelop_proto_rawDescData []byte
)

func file_Envelop_proto_rawDescGZIP() []byte {
	file_Envelop_proto_rawDescOnce.Do(func() {
		file_Envelop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Envelop_proto_rawDesc), len(file_Envelop_proto_rawDesc)))
	})
	return file_Envelop_proto_rawDescData
}

var file_Envelop_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Envelop_proto_goTypes = []any{
	(*Envelop)(nil), // 0: Envelop
}
var file_Envelop_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Envelop_proto_init() }
func file_Envelop_proto_init() {
	if File_Envelop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Envelop_proto_rawDesc), len(file_Envelop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Envelop_proto_goTypes,
		DependencyIndexes: file_Envelop_proto_depIdxs,
		MessageInfos:      file_Envelop_proto_msgTypes,
	}.Build()
	File_Envelop_proto = out.File
	file_Envelop_proto_goTypes = nil
	file_Envelop_proto_depIdxs = nil
}
