// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: ejemplo1.proto

package components

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mensaje struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texto         string                 `protobuf:"bytes,1,opt,name=texto,proto3" json:"texto,omitempty"`
	Numero        int32                  `protobuf:"varint,2,opt,name=numero,proto3" json:"numero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mensaje) Reset() {
	*x = Mensaje{}
	mi := &file_ejemplo1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensaje) ProtoMessage() {}

func (x *Mensaje) ProtoReflect() protoreflect.Message {
	mi := &file_ejemplo1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensaje.ProtoReflect.Descriptor instead.
func (*Mensaje) Descriptor() ([]byte, []int) {
	return file_ejemplo1_proto_rawDescGZIP(), []int{0}
}

func (x *Mensaje) GetTexto() string {
	if x != nil {
		return x.Texto
	}
	return ""
}

func (x *Mensaje) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

var File_ejemplo1_proto protoreflect.FileDescriptor

const file_ejemplo1_proto_rawDesc = "" +
	"\n" +
	"\x0eejemplo1.proto\x12\aejemplo\"7\n" +
	"\aMensaje\x12\x14\n" +
	"\x05texto\x18\x01 \x01(\tR\x05texto\x12\x16\n" +
	"\x06numero\x18\x02 \x01(\x05R\x06numeroB\x0fZ\rejemplo/pb;pbb\x06proto3"

var (
	file_ejemplo1_proto_rawDescOnce sync.Once
	file_ejemplo1_proto_rawDescData []byte
)

func file_ejemplo1_proto_rawDescGZIP() []byte {
	file_ejemplo1_proto_rawDescOnce.Do(func() {
		file_ejemplo1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ejemplo1_proto_rawDesc), len(file_ejemplo1_proto_rawDesc)))
	})
	return file_ejemplo1_proto_rawDescData
}

var file_ejemplo1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ejemplo1_proto_goTypes = []any{
	(*Mensaje)(nil), // 0: ejemplo.Mensaje
}
var file_ejemplo1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ejemplo1_proto_init() }
func file_ejemplo1_proto_init() {
	if File_ejemplo1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ejemplo1_proto_rawDesc), len(file_ejemplo1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ejemplo1_proto_goTypes,
		DependencyIndexes: file_ejemplo1_proto_depIdxs,
		MessageInfos:      file_ejemplo1_proto_msgTypes,
	}.Build()
	File_ejemplo1_proto = out.File
	file_ejemplo1_proto_goTypes = nil
	file_ejemplo1_proto_depIdxs = nil
}
